### ISSUE TITLE
Cannot import video files, only images

### ISSUE THREAD

**Issue by j-maas** [afouse/chronoviz#15]
The "Import Data..." file chooser only allows selecting image files, but video files are not selectable.

**Comment by afouse** [comment]
Partially addressed in 09fd98c93e479a19c0c86fe7021a0dbfcf895e77.

The file chooser now allows you to select video files, but they do not yet show up properly.

**Comment by j-maas** [comment]
It works for me. Can you confirm the same for you, too?

**Comment by j-maas** [comment]
It appears to be fixed now.
