### ISSUE TITLE
ChronoViz crashes when loading `.annotation` containing `annotations.xml`

### ISSUE THREAD

**Issue by j-maas** [afouse/chronoviz#4]
If the `.annotations` file contains at least one annotation, ChronoViz crashes when attempting to load it. The crash happens at [`[layer setFrame:CGRectMake(rect.origin.x, rect.origin.y, rect.size.width, rect.size.height)]`](https://github.com/afouse/chronoviz/blob/avkit-attempt/Classes/Visualizers/AnnotationVisualizer.m#L422) because `rect.origin.x` is `NaN`. This is because `[segment time]` is indefinite leading to [`CMTimeGetSeconds([segment time])`](https://github.com/afouse/chronoviz/blob/avkit-attempt/Classes/Visualizers/AnnotationVisualizer.m#L286) being `NaN` and stored in `rect.origin.x`.

I still need to investigate why `[segment time]` is indefinite.

## Reproduction
When opening a video and then closing the ChronoViz windows using the red button, when I reopen the `annotation` using the "Open Recent" menu, it crashes. The current time of the player is set to a large negative value. (The `.annotation` file will contain an `annotations.xml`.)

When instead of closing the windows using the red button I simply stop the execution in Xcode using the stop button, I can then reopen the file via "Open Recent" and it loads correctly. (The `.annotation` file will *not* contain an `annotations.xml`.)

Copying an empty (i.e. without elements in `<data>`) `annotations.xml` into an `.annotation` package does *not* produce the crash. If there is at least one `<event>` it will crash.

Example `annotations.xml` that produces a crash:
```
<?xml version="1.0" encoding="UTF-8"?>
<data>
    <event startTimeInterval="21" start="November 25 2016 14:24:03 GMT+0100" title="" annotation-modificationDate="June 26 2020 14:17:46 GMT+0200" annotation-modificationUser="Johannes Maas" annotation-category="Category 2"><category name="Category 2"></category>
    </event>
</data>
```

**Comment by Y0hy0h** [comment]
One of the symptoms is that the `TimelineView` when asked to `updatePlayheadPosition()` tries to determine the `playheadPosition()` using the `[[AppController currentApp] currentTime]`, which of course calls an `AVPlayerItem`'s `currentTime()`. For some reason, that player's `status` is `AVPlayerItemStatusUnknown`, i.e. not yet loaded.

**Comment by Y0hy0h** [comment]
I discovered that the saved `.annotation` package in its `annotations.xml` stores `nan` as the `startTimeInterval` and `endTimeInterval`.

**Comment by Y0hy0h** [comment]
I noticed that when stopping the app, the `.annotation` file did not contain `annotations.xml`. Copying an empty (i.e. without elements in `<data`) `annotations.xml` into the `.annotation` package does *not* produce the crash. If it contains one annotation, it crashes.

Example `annotations.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<data>
    <event startTimeInterval="21" start="November 25 2016 14:24:03 GMT+0100" title="" annotation-modificationDate="June 26 2020 14:17:46 GMT+0200" annotation-modificationUser="Johannes Maas" annotation-category="Category 2"><category name="Category 2"></category>
    </event>
</data>
```

**Comment by j-maas** [comment]
Worked around this issue with fe33da144cb0c1ad1ef2a0710fcd2e4df90efae8.
